### ISSUE TITLE
Process' death handling

### ISSUE THREAD

**Issue by shchurov** [Adyen/adyen-3ds2-android#8]
Looking at the challenge API it seems that SDK doesn't handle the situation when the process is being killed by the system.
Steps to reproduce:
1. set "Background process limit" to 0
2. start a challenge
3. switch to another app
4. switch back

As a result, it doesn't restore the challenge screen. Also I don't see how I can restore the original Transaction and pass it a new instance of ChallengeStatusReceiver. 
I can easily imagine this situation happen in real life when a user switches to a banking app and the phone is low on memory. 

SDK version: 2.1.0-rc01

EDIT: It also doesn't handle a config change (e.g. device language change) when activities are being recreated.

**Comment by ran-haveshush** [comment]
@shchurov thanks for the issue report.

The SDK doesn't support recovering and restoring the last state in case of a process kill,
since it's forbidden to persist the user and transaction data from security and PCI compliance concerns.

The recovery should come from the integrating App:
1. Close and dispose the current transaction.
2. Create a new transaction and re-challenge the user.

But while testing we noticed that the challenge activity is not recovering from screen rotation configuration changes which it should, so we will work on a fix for that.

Cheers,
Ran

**Comment by shchurov** [comment]
@ran-haveshush
In that case I don't think there's any sense in recovering the challenge activity because the caller activity most probably also has died and the callback is lost. 
Another concern is that if the system is low on memory and kills the process every time user switches the app it won't be possible to complete a transaction.

**Comment by ran-haveshush** [comment]
@shchurov,

"In that case I don't think there's any sense in recovering the challenge activity because the caller activity most probably also has died and the callback is lost."

The calling activity will recreate itself after the provided `ChallengeStatusReceiver` is finished, so there is a sense in restoring the challenge activity state.

"Another concern is that if the system is low on memory and kills the process every time user switches the app it won't be possible to complete a transaction."

You are right but that is an fairly extreme edge case.

I sent you a test version of the SDK with a challenge activity save/restore state fix.

Cheers,
Ran

**Comment by shchurov** [comment]
@ran-haveshush 
Sorry, don't see it anywhere. Can you send it again to mike@wolt.com?

Do you mean that `ChallengeStatusReceiver` and `Transaction` should be kept outside of my activity, like in some sort of singleton so I have access to them even if the activity instance is destroyed?
What about `currentActivity` param of `doChallenge`? Will SDK handle death of `currentActivity` instance properly?

**Comment by ran-haveshush** [comment]
@shchurov what I mean is that the  `ChallengeStatusReceiver#onComplete(...)` will be called before the calling activity `currentActivity` will be destroyed and recreated because of the screen orientation change, so the transaction will complete successfully, so you can handle the transaction result successfully.

As a best practice I would keep the `Transaction` instance in a the calling activity `ViewModel` so it will survive configuration changes and would use `LiveData` to communicate the Transaction state back to the UI.

FYI - The `currentActivity` instance is been keep inside a WeakReference instance member in the `Transaction`  instance to prevent memory leaks.

Cheers,
Ran

**Comment by shchurov** [comment]
@ran-haveshush  
Alright, makes sense now.

But getting back to process death: it's quite likely that no lifecycle callbacks are invoked when it happens, i.e. client app doesn't know when to close the transaction. So when I restore the app after process being recreated it shows the challenge activity with permanent loading.

**Comment by ran-haveshush** [comment]
@shchurov good point.

We have introduced a fix to the challenge activity behaviour.

Now when the challenge activity is recreated after a process kill, it will finish early so the foreground focus will transfer to the calling activity. The calling activity should close the previous transaction and create a new one.

I sent you a test SDK to check the new behaviour. 

Cheers,
Ran

**Comment by ran-haveshush** [comment]
Hi @shchurov the issues were fixed on version [2.1.0-rc02](https://github.com/Adyen/adyen-3ds2-android/releases/tag/2.1.0-rc02) .

Cheers,
Ran
